# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainmenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(800, 492)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainMenu.sizePolicy().hasHeightForWidth())
        MainMenu.setSizePolicy(sizePolicy)
        MainMenu.setMinimumSize(QtCore.QSize(800, 480))
        MainMenu.setMaximumSize(QtCore.QSize(800, 492))
        MainMenu.setBaseSize(QtCore.QSize(800, 480))
        self.mainMenuWidget = QtWidgets.QWidget(MainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainMenuWidget.sizePolicy().hasHeightForWidth())
        self.mainMenuWidget.setSizePolicy(sizePolicy)
        self.mainMenuWidget.setMinimumSize(QtCore.QSize(320, 480))
        self.mainMenuWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.mainMenuWidget.setBaseSize(QtCore.QSize(320, 480))
        self.mainMenuWidget.setObjectName("mainMenuWidget")
        self.scanItemFrame = QtWidgets.QFrame(self.mainMenuWidget)
        self.scanItemFrame.setGeometry(QtCore.QRect(130, 60, 231, 211))
        self.scanItemFrame.setMouseTracking(True)
        self.scanItemFrame.setAutoFillBackground(True)
        self.scanItemFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scanItemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scanItemFrame.setObjectName("scanItemFrame")
        self.scanItemLabel = QtWidgets.QLabel(self.scanItemFrame)
        self.scanItemLabel.setGeometry(QtCore.QRect(0, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.scanItemLabel.setFont(font)
        self.scanItemLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scanItemLabel.setObjectName("scanItemLabel")
        self.scanItemIcon = QtWidgets.QLabel(self.scanItemFrame)
        self.scanItemIcon.setGeometry(QtCore.QRect(40, 30, 141, 111))
        self.scanItemIcon.setText("")
        self.scanItemIcon.setPixmap(QtGui.QPixmap("img/icon_scan.png"))
        self.scanItemIcon.setScaledContents(True)
        self.scanItemIcon.setObjectName("scanItemIcon")
        self.washClothesFrame = QtWidgets.QFrame(self.mainMenuWidget)
        self.washClothesFrame.setGeometry(QtCore.QRect(490, 40, 231, 211))
        self.washClothesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.washClothesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.washClothesFrame.setObjectName("washClothesFrame")
        self.washClothesLabel = QtWidgets.QLabel(self.washClothesFrame)
        self.washClothesLabel.setGeometry(QtCore.QRect(0, 180, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.washClothesLabel.setFont(font)
        self.washClothesLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.washClothesLabel.setObjectName("washClothesLabel")
        self.washClothesIcon = QtWidgets.QLabel(self.washClothesFrame)
        self.washClothesIcon.setGeometry(QtCore.QRect(60, 50, 101, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.washClothesIcon.sizePolicy().hasHeightForWidth())
        self.washClothesIcon.setSizePolicy(sizePolicy)
        self.washClothesIcon.setText("")
        self.washClothesIcon.setPixmap(QtGui.QPixmap("img/icon_wash.png"))
        self.washClothesIcon.setScaledContents(True)
        self.washClothesIcon.setObjectName("washClothesIcon")
        self.viewEditItemFrame = QtWidgets.QFrame(self.mainMenuWidget)
        self.viewEditItemFrame.setGeometry(QtCore.QRect(140, 260, 231, 211))
        self.viewEditItemFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewEditItemFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewEditItemFrame.setObjectName("viewEditItemFrame")
        self.viewEditItemLabel = QtWidgets.QLabel(self.viewEditItemFrame)
        self.viewEditItemLabel.setGeometry(QtCore.QRect(0, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.viewEditItemLabel.setFont(font)
        self.viewEditItemLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.viewEditItemLabel.setObjectName("viewEditItemLabel")
        self.viewEditItemIcon = QtWidgets.QLabel(self.viewEditItemFrame)
        self.viewEditItemIcon.setGeometry(QtCore.QRect(60, 40, 111, 101))
        self.viewEditItemIcon.setText("")
        self.viewEditItemIcon.setPixmap(QtGui.QPixmap("img/icon_viewedit.png"))
        self.viewEditItemIcon.setScaledContents(True)
        self.viewEditItemIcon.setObjectName("viewEditItemIcon")
        self.settingsFrame = QtWidgets.QFrame(self.mainMenuWidget)
        self.settingsFrame.setGeometry(QtCore.QRect(480, 260, 231, 211))
        self.settingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settingsFrame.setObjectName("settingsFrame")
        self.settingsLabel = QtWidgets.QLabel(self.settingsFrame)
        self.settingsLabel.setGeometry(QtCore.QRect(0, 160, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.settingsLabel.setFont(font)
        self.settingsLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.settingsLabel.setObjectName("settingsLabel")
        self.settingsIcon = QtWidgets.QLabel(self.settingsFrame)
        self.settingsIcon.setGeometry(QtCore.QRect(60, 20, 121, 121))
        self.settingsIcon.setText("")
        self.settingsIcon.setPixmap(QtGui.QPixmap("img/icon_settings.png"))
        self.settingsIcon.setScaledContents(True)
        self.settingsIcon.setObjectName("settingsIcon")
        self.appTitleLabel = QtWidgets.QLabel(self.mainMenuWidget)
        self.appTitleLabel.setGeometry(QtCore.QRect(220, 10, 371, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.appTitleLabel.setFont(font)
        self.appTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.appTitleLabel.setObjectName("appTitleLabel")
        MainMenu.setCentralWidget(self.mainMenuWidget)
        self.mainToolBar = QtWidgets.QToolBar(MainMenu)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setMaximumSize(QtCore.QSize(0, 0))
        self.mainToolBar.setObjectName("mainToolBar")
        MainMenu.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Laundry Manager and Optimizer"))
        self.scanItemLabel.setText(_translate("MainMenu", "Scan Item"))
        self.washClothesLabel.setText(_translate("MainMenu", "Wash Clothes"))
        self.viewEditItemLabel.setText(_translate("MainMenu", "View/Edit Items"))
        self.settingsLabel.setText(_translate("MainMenu", "Settings"))
        self.appTitleLabel.setText(_translate("MainMenu", "Laundry Manager and Optimizer"))

