# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsmenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsMenu(object):
    def setupUi(self, SettingsMenu):
        SettingsMenu.setObjectName("SettingsMenu")
        SettingsMenu.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsMenu.sizePolicy().hasHeightForWidth())
        SettingsMenu.setSizePolicy(sizePolicy)
        SettingsMenu.setMinimumSize(QtCore.QSize(800, 480))
        SettingsMenu.setMaximumSize(QtCore.QSize(800, 512))
        SettingsMenu.setBaseSize(QtCore.QSize(800, 480))
        self.centralWidget = QtWidgets.QWidget(SettingsMenu)
        self.centralWidget.setMinimumSize(QtCore.QSize(320, 480))
        self.centralWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.centralWidget.setBaseSize(QtCore.QSize(320, 480))
        self.centralWidget.setObjectName("centralWidget")
        self.homeButton = QtWidgets.QLabel(self.centralWidget)
        self.homeButton.setGeometry(QtCore.QRect(660, 340, 131, 131))
        self.homeButton.setText("")
        self.homeButton.setPixmap(QtGui.QPixmap("img/icon_home.png"))
        self.homeButton.setScaledContents(True)
        self.homeButton.setObjectName("homeButton")
        self.brightnessSlider = QtWidgets.QSlider(self.centralWidget)
        self.brightnessSlider.setGeometry(QtCore.QRect(70, 70, 671, 51))
        self.brightnessSlider.setMaximum(255)
        self.brightnessSlider.setProperty("value", 75)
        self.brightnessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.brightnessSlider.setObjectName("brightnessSlider")
        self.brightnessPrompt = QtWidgets.QLabel(self.centralWidget)
        self.brightnessPrompt.setGeometry(QtCore.QRect(300, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.brightnessPrompt.setFont(font)
        self.brightnessPrompt.setAlignment(QtCore.Qt.AlignCenter)
        self.brightnessPrompt.setObjectName("brightnessPrompt")
        self.brightnessLvlLabel = QtWidgets.QLabel(self.centralWidget)
        self.brightnessLvlLabel.setGeometry(QtCore.QRect(300, 130, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.brightnessLvlLabel.setFont(font)
        self.brightnessLvlLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.brightnessLvlLabel.setObjectName("brightnessLvlLabel")
        self.deleteAllButton = QtWidgets.QPushButton(self.centralWidget)
        self.deleteAllButton.setGeometry(QtCore.QRect(290, 200, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.deleteAllButton.setFont(font)
        self.deleteAllButton.setObjectName("deleteAllButton")
        self.fastScanButton = QtWidgets.QRadioButton(self.centralWidget)
        self.fastScanButton.setGeometry(QtCore.QRect(320, 340, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.fastScanButton.setFont(font)
        self.fastScanButton.setChecked(True)
        self.fastScanButton.setObjectName("fastScanButton")
        self.accurateScanButton = QtWidgets.QRadioButton(self.centralWidget)
        self.accurateScanButton.setGeometry(QtCore.QRect(320, 370, 161, 17))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.accurateScanButton.setFont(font)
        self.accurateScanButton.setObjectName("accurateScanButton")
        self.scanModeLabel = QtWidgets.QLabel(self.centralWidget)
        self.scanModeLabel.setGeometry(QtCore.QRect(290, 300, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(14)
        self.scanModeLabel.setFont(font)
        self.scanModeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.scanModeLabel.setObjectName("scanModeLabel")
        SettingsMenu.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(SettingsMenu)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setMaximumSize(QtCore.QSize(0, 0))
        self.mainToolBar.setObjectName("mainToolBar")
        SettingsMenu.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(SettingsMenu)
        QtCore.QMetaObject.connectSlotsByName(SettingsMenu)

    def retranslateUi(self, SettingsMenu):
        _translate = QtCore.QCoreApplication.translate
        SettingsMenu.setWindowTitle(_translate("SettingsMenu", "Laundry Manager and Optimizer"))
        self.brightnessPrompt.setText(_translate("SettingsMenu", "Brightness"))
        self.brightnessLvlLabel.setText(_translate("SettingsMenu", "Current level: 30"))
        self.deleteAllButton.setText(_translate("SettingsMenu", "Remove All Items"))
        self.fastScanButton.setText(_translate("SettingsMenu", "Fast Scannning"))
        self.accurateScanButton.setText(_translate("SettingsMenu", "Accurate Scanning"))
        self.scanModeLabel.setText(_translate("SettingsMenu", "Symbol Scan Mode"))

