# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vieweditmenu.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ViewEditMenu(object):
    def setupUi(self, ViewEditMenu):
        ViewEditMenu.setObjectName("ViewEditMenu")
        ViewEditMenu.resize(800, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ViewEditMenu.sizePolicy().hasHeightForWidth())
        ViewEditMenu.setSizePolicy(sizePolicy)
        ViewEditMenu.setMinimumSize(QtCore.QSize(800, 480))
        ViewEditMenu.setMaximumSize(QtCore.QSize(800, 512))
        ViewEditMenu.setBaseSize(QtCore.QSize(800, 480))
        self.centralWidget = QtWidgets.QWidget(ViewEditMenu)
        self.centralWidget.setMinimumSize(QtCore.QSize(320, 480))
        self.centralWidget.setMaximumSize(QtCore.QSize(800, 480))
        self.centralWidget.setBaseSize(QtCore.QSize(320, 480))
        self.centralWidget.setObjectName("centralWidget")
        self.homeButton = QtWidgets.QLabel(self.centralWidget)
        self.homeButton.setGeometry(QtCore.QRect(660, 340, 131, 131))
        self.homeButton.setText("")
        self.homeButton.setPixmap(QtGui.QPixmap("img/icon_home.png"))
        self.homeButton.setScaledContents(True)
        self.homeButton.setObjectName("homeButton")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 20, 801, 461))
        font = QtGui.QFont()
        font.setFamily("Roboto Black")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.blTab = QtWidgets.QWidget()
        self.blTab.setObjectName("blTab")
        self.scrollArea = QtWidgets.QScrollArea(self.blTab)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 801, 431))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 429))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setGeometry(QtCore.QRect(0, 0, 791, 80))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(630, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 71, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("img/bleach_no.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 71, 61))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("img/iron_low.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(350, 10, 71, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("img/wash_40c.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setGeometry(QtCore.QRect(0, 80, 791, 80))
        self.widget_2.setObjectName("widget_2")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 10, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(150, 10, 71, 61))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("img/bleach_no.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_2)
        self.label_7.setGeometry(QtCore.QRect(250, 10, 71, 61))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("img/iron_low.png"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.widget_2)
        self.label_8.setGeometry(QtCore.QRect(350, 10, 71, 61))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("img/wash_40c.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.blTab, "")
        self.brTab = QtWidgets.QWidget()
        self.brTab.setObjectName("brTab")
        self.tabWidget.addTab(self.brTab, "")
        self.tlTab = QtWidgets.QWidget()
        self.tlTab.setObjectName("tlTab")
        self.tabWidget.addTab(self.tlTab, "")
        self.trTab = QtWidgets.QWidget()
        self.trTab.setObjectName("trTab")
        self.tabWidget.addTab(self.trTab, "")
        self.tabWidget.raise_()
        self.homeButton.raise_()
        ViewEditMenu.setCentralWidget(self.centralWidget)
        self.mainToolBar = QtWidgets.QToolBar(ViewEditMenu)
        self.mainToolBar.setEnabled(False)
        self.mainToolBar.setMaximumSize(QtCore.QSize(0, 0))
        self.mainToolBar.setObjectName("mainToolBar")
        ViewEditMenu.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(ViewEditMenu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ViewEditMenu)

    def retranslateUi(self, ViewEditMenu):
        _translate = QtCore.QCoreApplication.translate
        ViewEditMenu.setWindowTitle(_translate("ViewEditMenu", "Laundry Manager and Optimizer"))
        self.label.setText(_translate("ViewEditMenu", "Item #1"))
        self.pushButton.setText(_translate("ViewEditMenu", "Delete Item"))
        self.label_5.setText(_translate("ViewEditMenu", "Item #2"))
        self.pushButton_2.setText(_translate("ViewEditMenu", "Delete Item"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blTab), _translate("ViewEditMenu", "Bottom-Left Section"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.brTab), _translate("ViewEditMenu", "Bottom-Right Section"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tlTab), _translate("ViewEditMenu", "Top-Left Section"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.trTab), _translate("ViewEditMenu", "Top-Right Section"))

